# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gvtnAbMRkRSrBV0idCjjmvddhZDmKECT
"""

from google.colab import files
uploaded = files.upload()

!pip install streamlit tensorflow pillow numpy --quiet

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

model = tf.keras.models.load_model('/content/plant_disease_multiclass_model.h5', compile=False)

class_labels = [
    'Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust',
    'Cherry_(including_sour)___Powdery_mildew', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
    'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight',
    'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
    'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Pepper__bell___Bacterial_spot',
    'Potato___Early_blight', 'Potato___Late_blight', 'Squash___Powdery_mildew',
    'Strawberry___Leaf_scorch', 'Tomato_Bacterial_spot', 'Tomato_Early_blight',
    'Tomato_Late_blight', 'Tomato_Leaf_Mold', 'Tomato_Septoria_leaf_spot',
    'Tomato_Spider_mites_Two_spotted_spider_mite', 'Tomato__Target_Spot',
    'Tomato__Tomato_YellowLeaf__Curl_Virus', 'Tomato__Tomato_mosaic_virus', 'healthy'
]

malayalam_labels = [
    'ആപ്പിൾ___ആപ്പിൾ സ്കാബ്', 'ആപ്പിൾ___ബ്ലാക്ക് റോട്ട്', 'ആപ്പിൾ___സിഡാർ ആപ്പിൾ ജംഗ്',
    'ചെറി___പൗഡറി മിൽഡ്യൂ', 'മകാൺ___സർക്കോസ്പോറ ലീഫ് സ്പോട്ട്/ഗ്രേ ലീഫ് സ്പോട്ട്',
    'മകാൺ___സാധാരണ ജംഗ്', 'മകാൺ___നോർത്ത് ലീഫ് ബ്ലൈറ്റ്',
    'ദ്രാക്ഷി___ബ്ലാക്ക് റോട്ട്', 'ദ്രാക്ഷി___എസ്ക (ബ്ലാക്ക് മീസൽ)', 'ദ്രാക്ഷി___ലീഫ് ബ്ലൈറ്റ്',
    'ഓറഞ്ച്___ഹൗങ്‌ലോങ്ങ്ബിങ്ങ്', 'പീച്ച്___ബാക്ടീരിയൽ സ്പോട്ട്', 'ക്യാപ്സിക്കം___ബാക്ടീരിയൽ സ്പോട്ട്',
    'ഉരുളക്കിഴങ്ങ്___ആദ്യ ബ്ലൈറ്റ്', 'ഉരുളക്കിഴങ്ങ്___ലേറ്റ് ബ്ലൈറ്റ്', 'സ്ക്വാഷ്___പൗഡറി മിൽഡ്യൂ',
    'സ്ട്രോബെറി___ലീഫ് സ്കോർച്ച്', 'തക്കാളി___ബാക്ടീരിയൽ സ്പോട്ട്', 'തക്കാളി___ആദ്യ ബ്ലൈറ്റ്',
    'തക്കാളി___ലേറ്റ് ബ്ലൈറ്റ്', 'തക്കാളി___ലീഫ് മോൾഡ്', 'തക്കാളി___സെപ്ടോറിയ ലീഫ് സ്പോട്ട്',
    'തക്കാളി___സ്പൈഡർ മൈറ്റ്സ്', 'തക്കാളി___ടാർഗറ്റ് സ്പോട്ട്',
    'തക്കാളി___പച്ചമഞ്ഞ കറുപ്പ് വൈറസ്', 'തക്കാളി___മോസൈക് വൈറസ്', 'ആരോഗ്യമുള്ള'
]

spanish_labels = [
    'Manzana___Costra del manzano', 'Manzana___Podredumbre negra', 'Manzana___Royas del manzano',
    'Cereza___Mildiu polvoriento', 'Maíz___Mancha foliar gris',
    'Maíz___Royas comunes', 'Maíz___Tizón de la hoja del norte',
    'Uva___Podredumbre negra', 'Uva___Esca (Measles negras)', 'Uva___Tizón de la hoja',
    'Naranja___Huanglongbing (Greening)', 'Melocotón___Mancha bacteriana', 'Pimiento___Mancha bacteriana',
    'Papa___Tizón temprano', 'Papa___Tizón tardío', 'Calabaza___Mildiu polvoriento',
    'Fresa___Escaldadura de la hoja', 'Tomate___Mancha bacteriana', 'Tomate___Tizón temprano',
    'Tomate___Tizón tardío', 'Tomate___Moho de la hoja', 'Tomate___Mancha foliar Septoria',
    'Tomate___Ácaros de dos puntos', 'Tomate___Mancha objetivo',
    'Tomate___Virus del rizado amarillo', 'Tomate___Virus del mosaico', 'Saludable'
]

st.set_page_config(page_title="🌿 Plant Disease Detector (Multilingual)", layout="centered")
st.title("🌿 Plant Disease Detection App (Multilingual)")
st.write("Upload multiple leaf images 📷 and detect diseases in English, Malayalam, or Spanish! 🌎")

language = st.selectbox("🌐 Choose Language:", ["English", "Malayalam", "Spanish"])

uploaded_files = st.file_uploader("📷 Upload Multiple Leaf Images", accept_multiple_files=True, type=["jpg", "jpeg", "png"])

if st.button("🚀 Predict Diseases"):
    if uploaded_files:
        for uploaded_file in uploaded_files:
            img = Image.open(uploaded_file).convert('RGB')
            img_resized = img.resize((128, 128))
            img_array = np.expand_dims(np.array(img_resized) / 255.0, axis=0)

            prediction = model.predict(img_array)
            predicted_class_index = np.argmax(prediction)

            if language == "English":
                label = class_labels[predicted_class_index]
            elif language == "Malayalam":
                label = malayalam_labels[predicted_class_index]
            elif language == "Spanish":
                label = spanish_labels[predicted_class_index]
            else:
                label = class_labels[predicted_class_index]

            confidence = np.max(prediction) * 100

            st.image(img, caption=f"🌿 Prediction: {label} (Confidence: {confidence:.2f}%)", width=300)
            st.markdown(f"### 🌱 {label}")
            st.markdown(f"🔵 Confidence: {confidence:.2f}%")
            st.markdown("---")
    else:
        st.warning("⚠️ Please upload at least one leaf image first.")

